/*
 * This file has been automatically generated by the WICED Smart Designer.
 * Definitions for constants used in the device's GATT database and function
 * prototypes.
 *
 */

// beacon_scanner_db.h

#ifndef __GATT_DATABASE_H__
#define __GATT_DATABASE_H__

// UART is enabled in device settings
#define GATT_DB_ENABLE_UART

#define UUID_SERVICE_GAP                                       0x1800
#define UUID_CHARACTERISTIC_DEVICE_NAME                        0x2A00
#define UUID_CHARACTERISTIC_APPEARANCE                         0x2A01
#define UUID_SERVICE_GATT                                      0x1801
#define UUID_SERVICE_DEVICE_INFORMATION                        0x180A
#define UUID_CHARACTERISTIC_MANUFACTURER_NAME_STRING           0x2A29
#define UUID_CHARACTERISTIC_MODEL_NUMBER_STRING                0x2A24
#define UUID_CHARACTERISTIC_SOFTWARE_REVISION_STRING           0x2A28

// ***** Primary Service 'Generic Access'
#define HDLS_GENERIC_ACCESS                                    0x0001
// ----- Characteristic 'Device Name'
#define HDLC_GENERIC_ACCESS_DEVICE_NAME                        0x0002
#define HDLC_GENERIC_ACCESS_DEVICE_NAME_VALUE                  0x0003
// ----- Characteristic 'Appearance'
#define HDLC_GENERIC_ACCESS_APPEARANCE                         0x0004
#define HDLC_GENERIC_ACCESS_APPEARANCE_VALUE                   0x0005

// ***** Primary Service 'Generic Attribute'
#define HDLS_GENERIC_ATTRIBUTE                                 0x0006

// ***** Primary Service 'Device Information'
#define HDLS_DEVICE_INFORMATION                                0x0100
// ----- Characteristic 'Manufacturer Name String'
#define HDLC_DEVICE_INFORMATION_MANUFACTURER_NAME_STRING       0x0101
#define HDLC_DEVICE_INFORMATION_MANUFACTURER_NAME_STRING_VALUE 0x0102
// ----- Characteristic 'Model Number String'
#define HDLC_DEVICE_INFORMATION_MODEL_NUMBER_STRING            0x0103
#define HDLC_DEVICE_INFORMATION_MODEL_NUMBER_STRING_VALUE      0x0104
// ----- Characteristic 'Software Revision String'
#define HDLC_DEVICE_INFORMATION_SOFTWARE_REVISION_STRING       0x0105
#define HDLC_DEVICE_INFORMATION_SOFTWARE_REVISION_STRING_VALUE 0x0106

#pragma pack(1)
// Host information for NVRAM
typedef PACKED struct
{
    // BD address of the bonded host
    BD_ADDR  bdaddr;
}  __HOSTINFO;
#pragma pack()

// External definitions
extern const UINT8  gatt_database[];
extern const UINT16 gatt_database_len;
extern UINT16       beacon_scanner_connection_handle;         // HCI handle of connection, not zero when connected
extern const BLE_PROFILE_GPIO_CFG
                    beacon_scanner_gpio_cfg;                  // Defines GPIO configuration used by the application
extern BD_ADDR      beacon_scanner_remote_addr;               // Address of currently connected client
extern UINT8        beacon_scanner_uuid_main_service[2];      // Main service
// Pointer to the generated part of hostinfo
extern __HOSTINFO   *p_hostinfo_generated;

// Functions definitions

// Will be called on indication confirmation
// Registers timer. Should be called from beacon_scanner_create()
extern void beacon_scanner_reg_timer();
// Initializes persistent values in the hostinfo to add bonded peer
extern void beacon_scanner_add_bond(UINT8 *bda);
// Prepares generated code for connection - writes persistent values from __HOSTINFO to GATT DB
extern void __on_connection_up();
// Sends notifications or/and indications for every client configuration descriptor
// Updates __HOSTINFO by the value written by peer.
// Returns true if any persistent value is changed
extern BOOL __write_handler(UINT16 handle, int len, UINT8 *attrPtr);


// ------------------- You have to implement these functions ----------------

// Custom function to be called every 1 s
extern void beacon_scanner_timer_1s();


// ------------------- You can call these functions ----------------

// It should be called when 'Device Name' is changed
extern BOOL store_in_db_generic_access_device_name(UINT8* p_value, UINT8 value_len);

// It should be called when 'Appearance' is changed
extern BOOL store_in_db_generic_access_appearance(UINT8* p_value, UINT8 value_len);

// It should be called when 'Manufacturer Name String' is changed
extern BOOL store_in_db_device_information_manufacturer_name_string(UINT8* p_value, UINT8 value_len);

// It should be called when 'Model Number String' is changed
extern BOOL store_in_db_device_information_model_number_string(UINT8* p_value, UINT8 value_len);

// It should be called when 'Software Revision String' is changed
extern BOOL store_in_db_device_information_software_revision_string(UINT8* p_value, UINT8 value_len);

#endif /* __GATT_DATABASE_H__ */
